name: Docker

on:
  push:
    branches: [ master ]
    paths:
      - 'Dockerfile'
      - '.github/workflows/docker-image.yml'
  pull_request:
    branches: [ master ]
  schedule:
    - cron: '0 0 1 */2 *' # bimonthly check

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v2
      - name: Build the Docker image
        run: |
          wget https://unidic.ninjal.ac.jp/unidic_archive/cwj/2.1.2/unidic-mecab_kana-accent-2.1.2_src.zip
          docker build -t tdmelodic:$(date +%s) . --no-cache
